PROJECT_NAME: django-starter
HOST_NAME: django-starter # not required for k8s-only setup
NAMESPACE: django-starter
IMAGE: rehive/django-starter
CELERY_ID: django-starter
VIRTUAL_HOST: starter.rehive.com
VENV_PYTHON: ~/anaconda/envs/zapgo-core/bin/python3.5
ENV_FILE: .local.env
POSTGRES_PORT: 5125