PROJECT_NAME: django-starter
NAMESPACE: django-starter
IMAGE: rehive/django-starter
HOST_NAME: starter-server
BASE_IMAGE: rehive/django-starter
VIRTUAL_HOST: starter.rehive.com
ENV_FILE: .production.env
CELERY_ID: django-starter
GCLOUD_STATIC_BUCKET: starter
POSTGRES_PORT: 5125
