PROJECT_NAME: django-starter
NAMESPACE: django-starter
IMAGE: rehive/django-starter
HOST_NAME: escrow
BASE_IMAGE: rehive/django-starter
VIRTUAL_HOST: escrow.rehive.io
ENV_FILE: .production.env
CELERY_ID: django-starter
GCLOUD_STATIC_BUCKET: escrow
POSTGRES_PORT: 5125