version: "2.1"

services:
  webapp:
    image: ${IMAGE_NAME}:${VERSION}
    user: nobody
    env_file: $PWD/.env
    network_mode: "bridge"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: always
