version: "2.1"

services:
  webapp:
    extends:
      service: webapp
      file: ./docker-services.yml
    command: /bin/sh -c "gunicorn config.wsgi:application --config file:config/gunicorn.py"
    links:
      - postgres
    ports:
      - 8010:8000
    network_mode: bridge

  worker:
    network_mode: bridge
    extends:
        service: webapp
        file: ./docker-services.yml
    command: /bin/sh -c "celery -A config.celery worker --loglevel=INFO --concurrency=4 -Q general-${CELERY_ID}"
    links:
      - postgres

  postgres:
    image: postgres:9.5
    network_mode: bridge
    volumes_from:
      - db_data
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: always

  db_data:
    image: postgres
    command: echo "DB data volume!"
    volumes:
      - /var/lib/postgresql/data
