version: "2.1"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-volume:/etc/nginx/vhost.d
      - nginx-volume:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-volume:/etc/nginx/certs
    network_mode: "bridge"
    restart: always

  letsencrypt-plugin:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - "nginx-proxy"
    network_mode: "bridge"
    restart: always

volumes:
  nginx-volume:
