# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-12 15:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_code', models.CharField(db_index=True, max_length=200, null=True, unique=True)),
                ('address', models.CharField(max_length=300, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('confirmations', models.IntegerField(blank=True, db_index=True, null=True)),
                ('notifications', models.IntegerField(blank=True, db_index=True, null=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('response_code', models.CharField(max_length=5, null=True)),
                ('status', models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Complete', 'Complete')], db_index=True, max_length=24, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('address', models.CharField(db_index=True, max_length=300, unique=True)),
                ('last_block', models.IntegerField(blank=True, null=True)),
                ('confirmations', models.IntegerField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='webhook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitcoin_monitoring.Webhook'),
        ),
    ]
