# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='secret',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
