# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_monitoring', '0002_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
