# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-17 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_monitoring', '0003_auto_20170412_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='webhook_id',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
