# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_monitoring', '0004_webhook_webhook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='address',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='confirmations',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
