# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-17 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_monitoring', '0005_auto_20170417_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_code',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('tx_code', 'webhook')]),
        ),
    ]
